#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <stdint.h>

#define MAX_EVENTS 100
#define MASTER_RECEIVE_BUFFER_SIZE 512
#define MAX_NODES 5
#define MAX_FILE_SIZE 1024
#define MAX_DATA_BUFFER_IN_STRUCT 256

#define MAX_SIO_WORKERS 2
#define MAX_LOGIC_WORKERS 4
#define MAX_COW_WORKERS 45
#define MAX_DBR_WORKERS 5
#define MAX_DBW_WORKERS 1
#define MAX_CLIENTS_PER_SIO_WORKER 8
#define MAX_MASTER_CONCURRENT_SESSIONS (MAX_SIO_WORKERS * MAX_CLIENTS_PER_SIO_WORKER)
#define MAX_DOWNSTREAM_NODES_LIMIT 10

#define RATELIMITSEC 5
#define WORKER_HEARTBEATSEC_NODE_HEARTBEATSEC_TIMEOUT 5
#define MASTER_CHECK_HEALTHY_X 3
#define WORKER_HEARTBEATSEC_TIMEOUT MASTER_CHECK_HEALTHY_X * WORKER_HEARTBEATSEC_NODE_HEARTBEATSEC_TIMEOUT
#define HEARTBEAT_JITTER_PERCENTAGE 0.2
#define RAND_MAX_DOUBLE ((double)RAND_MAX)
#define INITIAL_MILISECONDS_PER_UNIT 5

#define IP_ADDRESS_LEN 16
#define DOUBLE_ARRAY_SIZE 8

#define IPC_LENGTH_PREFIX_BYTES sizeof(uint32_t)

#define IPC_VERSION_BYTES 2
#define IPC_VERSION_MAJOR 0x00
#define IPC_VERSION_MINOR 0x01

#define NODE_VERSION 1
#define NODE_FILE_MAGIC "NODEKEYS"
#define NODE_KEYFILE_PATH "./database/NODE.keys"

#endif
