#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_EVENTS 10
#define MASTER_RECEIVE_BUFFER_SIZE 512
#define MAX_PEERS 5
#define IP_STRLEN 16
#define MAX_FILE_SIZE 1024
#define MAX_DATA_BUFFER_IN_STRUCT 256

#define MAX_SIO_WORKERS 2
#define MAX_LOGIC_WORKERS 4
#define MAX_COW_WORKERS 50
#define MAX_CLIENTS_PER_SIO_WORKER 25
#define MAX_MASTER_CONCURRENT_SESSIONS (MAX_SIO_WORKERS * MAX_CLIENTS_PER_SIO_WORKER)

#endif
