#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <stdint.h>

#define MAX_EVENTS 100
#define MAX_BOOTSTRAP_NODES 313
#define MAX_BOOTSTRAP_FILE_SIZE 1024

#define MAX_SIO_WORKERS 2
#define MAX_LOGIC_WORKERS 6
#define MAX_COW_WORKERS 6
#define MAX_DBR_WORKERS 6
#define MAX_DBW_WORKERS 1
#define MAX_CONNECTION_PER_SIO_WORKER 25
#define MAX_CONNECTION_PER_COW_WORKER 55
#define MAX_MASTER_SIO_SESSIONS (MAX_SIO_WORKERS * MAX_CONNECTION_PER_SIO_WORKER)
#define MAX_MASTER_COW_SESSIONS (MAX_COW_WORKERS * MAX_CONNECTION_PER_COW_WORKER)
#define MAX_DOWNSTREAM_NODES_LIMIT 25

#define RATELIMITSEC 5
#define WORKER_HEARTBEATSEC_NODE_HEARTBEATSEC_TIMEOUT 3
#define MASTER_CHECK_HEALTHY_X 3
#define WORKER_HEARTBEATSEC_TIMEOUT MASTER_CHECK_HEALTHY_X * WORKER_HEARTBEATSEC_NODE_HEARTBEATSEC_TIMEOUT
#define HEARTBEAT_JITTER_PERCENTAGE 0.2
#define RAND_MAX_DOUBLE ((double)RAND_MAX)
#define INITIAL_MILISECONDS_PER_UNIT 5

#define IPV6_ADDRESS_LEN 16
#define IPV4_ADDRESS_LEN 4
#define SOCKADDR_IN6_SIZE (2 + 2 + 4 + 16 + 4)
#define DOUBLE_ARRAY_SIZE 8

#define IPC_LENGTH_PREFIX_BYTES sizeof(uint32_t)

#define IPC_VERSION_BYTES 2
#define IPC_VERSION_MAJOR 0x00
#define IPC_VERSION_MINOR 0x01

#define KALMAN_CALIBRATION_SAMPLES 20
#define KALMAN_ALPHA_EWMA 0.2f
#define HEALTHY_THRESHOLD 75

#define HASHES_BYTES 32
#define AES_NONCE_BYTES 12
#define AES_TAG_BYTES 16
//======================================================================
// OriLink
//======================================================================
#define ORILINK_VERSION_BYTES 2
#define ORILINK_VERSION_MAJOR 0x00
#define ORILINK_VERSION_MINOR 0x01
#define ORILINK_MAX_PACKET_SIZE 1400

#define MAX_SESSIONS 10
#define MAX_EPOLL_EVENTS 10
#define PACKET_TIMEOUT_SEC 2
#define CUBIC_BETA 0.7
#define CUBIC_C 0.4
#define NUM_STREAMS 2

#define MAX_PAYLOAD_SIZE 1384
#define KEEPALIVE_INTERVAL_SEC 15

#define RTT_ALPHA 0.125
#define RTT_BETA  0.25
#define RTO_MIN   0.2
#define RTO_MAX   60.0
//======================================================================

#define NODE_VERSION 1
#define NODE_FILE_MAGIC "NODEKEYS"
#define NODE_KEYFILE_PATH "./database/NODE.keys"

#endif
