#ifndef PQC_H
#define PQC_H

#include <stdint.h>
#include <crypto_sign/falcon-padded-512/clean/api.h>
#include <crypto_sign/ml-dsa-87/clean/api.h>
#include <crypto_kem/ml-kem-1024/clean/api.h>
#include <common/fips202.h>
#include "types.h"

#define KEM_ALGO MLKEM1024
#define SIGN_ALGO FALCONPADDED512

#if defined(KEM_ALGO) && (KEM_ALGO == MLKEM1024)
	#define KEM_PUBLICKEY_BYTES PQCLEAN_MLKEM1024_CLEAN_CRYPTO_PUBLICKEYBYTES
	#define KEM_PRIVATEKEY_BYTES PQCLEAN_MLKEM1024_CLEAN_CRYPTO_SECRETKEYBYTES
	#define KEM_CIPHERTEXT_BYTES PQCLEAN_MLKEM1024_CLEAN_CRYPTO_CIPHERTEXTBYTES
	#define KEM_SHAREDSECRET_BYTES PQCLEAN_MLKEM1024_CLEAN_CRYPTO_BYTES
	#define KEM_GENERATE_KEYPAIR(a, b) PQCLEAN_MLKEM1024_CLEAN_crypto_kem_keypair(a, b)
	#define KEM_ENCODE_SHAREDSECRET(a, b, c) PQCLEAN_MLKEM1024_CLEAN_crypto_kem_enc(a, b, c)
	#define KEM_DECODE_SHAREDSECRET(a, b, c) PQCLEAN_MLKEM1024_CLEAN_crypto_kem_dec(a, b, c)
#endif

#if defined(SIGN_ALGO) && (SIGN_ALGO == FALCONPADDED512)
	#define SIGN_PUBLICKEY_BYTES PQCLEAN_FALCONPADDED512_CLEAN_CRYPTO_PUBLICKEYBYTES
	#define SIGN_PRIVATEKEY_BYTES PQCLEAN_FALCONPADDED512_CLEAN_CRYPTO_SECRETKEYBYTES
	#define SIGN_GENERATE_SIGNATURE_BBYTES PQCLEAN_FALCONPADDED512_CLEAN_CRYPTO_BYTES
	#define SIGN_GENERATE_KEYPAIR(a, b) PQCLEAN_FALCONPADDED512_CLEAN_crypto_sign_keypair(a, b)
	#define SIGN_GENERATE_SIGNATURE(a, b, c, d, e) PQCLEAN_FALCONPADDED512_CLEAN_crypto_sign_signature(a, b, c, d, e)
	#define SIGN_VERIFY_SIGNATURE(a, b, c, d, e) PQCLEAN_FALCONPADDED512_CLEAN_crypto_sign_verify(a, b, c, d, e)
#elif defined(SIGN_ALGO) && (SIGN_ALGO == MLDSA87)
	#define SIGN_PUBLICKEY_BYTES PQCLEAN_MLDSA87_CLEAN_CRYPTO_PUBLICKEYBYTES
	#define SIGN_PRIVATEKEY_BYTES PQCLEAN_MLDSA87_CLEAN_CRYPTO_SECRETKEYBYTES
	#define SIGN_GENERATE_SIGNATURE_BBYTES PQCLEAN_MLDSA87_CLEAN_CRYPTO_BYTES
	#define SIGN_GENERATE_KEYPAIR(a, b) PQCLEAN_MLDSA87_CLEAN_crypto_sign_keypair(a, b)
	#define SIGN_GENERATE_SIGNATURE(a, b, c, d, e) PQCLEAN_MLDSA87_CLEAN_crypto_sign_signature(a, b, c, d, e)
	#define SIGN_VERIFY_SIGNATURE(a, b, c, d, e) PQCLEAN_MLDSA87_CLEAN_crypto_sign_verify(a, b, c, d, e)
#endif

#endif
